name: Java CI with Maven

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
# Checkout source code
    - uses: actions/checkout@v2

# Cache maven stuff
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

# if below step is skipped this build is a tag build. Can be used for skipping other steps.
    - name: Is Tag Build
      id: tag
      if:  ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Build and test
      run: ./build/build.sh

#    - name: Generate Jacoco Badge
#      id: jacoco
#      uses: cicirello/jacoco-badge-generator@v1.0.0
#      with:
#        jacoco-csv-file: testreport/target/site/jacoco-aggregate/jacoco.csv
#
#    - name: Log coverage percentage
#      run: |
#        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
#
#    - name: Update coverage badge
#      if: ${{ steps.tag.conclusion == 'skipped' }}
#      run: ./build/badge-update.sh
#
#    - name: Upload Jacoco coverage report
#      uses: actions/upload-artifact@v2
#      with:
#        name: jacoco-report
#        path: testreport/target/site/jacoco-aggregate/

    - name: Deploy
      if: ${{ steps.tag.conclusion == 'skipped' }}
      run: ./build/maven-run.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}